[versions]
kotlin = "2.2.21"
ktlintGradlePlugin = "14.0.1"

[libraries]
kotest = "io.kotest:kotest-assertions-core:6.0.7"
ktlint = "com.pinterest.ktlint:ktlint-cli:1.7.1"
ktlintGradlePlugin = { module = "org.jlleitschuh.gradle:ktlint-gradle", version.ref = "ktlintGradlePlugin" }
coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2"
okhttp = "com.squareup.okhttp3:okhttp:5.3.2"
clikt = "com.github.ajalt.clikt:clikt:5.0.3"
kotlinPoet = "com.squareup:kotlinpoet:2.2.0"

jupiter = "org.junit.jupiter:junit-jupiter:6.0.1"

serialization = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.9.0"
kotlin-jvmPlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintGradlePlugin" }
jetbrains-compose = {id="org.jetbrains.compose", version="1.9.3"}
